version: '3.7'

services:
  django_gunicorn:
    image: jdevries3133/smg_gunicorn
    build:
      context: .
    volumes:
      - static:/static
    env_file:
      - .env.django
      - ./db/.env.db
    ports:
      - "8000:8000"
    depends_on:
      - db
  nginx:
    image: jdevries3133/smg_nginx
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn
  db:
    image: jdevries3133/smg_db
    build: ./db
    restart: always
    env_file:
      - ./db/.env.db


volumes:
  static:

