version: "3.8"

services:
  db:
    image: mysql:8.0.21
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_USER: "jack"
      MYSQL_PASSWORD: "albuscute"
      MYSQL_DATABASE: "songmaker"
  web:
    build: ./django_smg
    container_name: django_smg
    volumes:
      - .:/django_smg
    ports:
      - "8000:8000"
    depends_on:
      - db
